name: Test
on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Build & Lint
        run: |
          npm ci
          npm run build
          npm run lint
